server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.example.demo.pojoCompanyDao
  mapper-locations: classpath:/mapper/*.xml
logging:
  file:
    name: log/log.log
  level:
    root: info
    com.example.demo: debug
